/*!
 * LeoAI Chat Widget
 * Embed with: <script src="https://your-cdn/chatbot.js" data-domain="yourdomain.com"></script>
 */
(function () {
  'use strict';

  const BACKEND_URL = window.LEO_BACKEND_URL || 'https://your-backend-url.com';
  const domain = document.currentScript?.getAttribute('data-domain') || window.location.hostname;
  const SESSION_KEY = `leo_session_${domain}`;

  // --- Session token ---
  function getSessionToken() {
    let token = localStorage.getItem(SESSION_KEY);
    if (!token) {
      token = 'leo_' + Math.random().toString(36).slice(2) + Date.now().toString(36);
      localStorage.setItem(SESSION_KEY, token);
    }
    return token;
  }

  const sessionToken = getSessionToken();

  // --- Socket.io for real-time owner replies ---
  function initSocket() {
    const script = document.createElement('script');
    script.src = BACKEND_URL + '/socket.io/socket.io.js';
    script.onload = () => {
      const socket = window.io(BACKEND_URL);
      socket.emit('join', sessionToken);
      socket.on('owner_reply', ({ message }) => {
        appendMessage('owner_reply', message);
        appendMessage('assistant', `Great news! The team just got back to you — see their reply above. Is there anything else I can help with?`);
      });
    };
    document.head.appendChild(script);
  }

  // --- Inject styles ---
  const style = document.createElement('link');
  style.rel = 'stylesheet';
  style.href = BACKEND_URL + '/chatbot.css';
  document.head.appendChild(style);

  // --- Build widget HTML ---
  const container = document.createElement('div');
  container.id = 'leo-widget';
  container.innerHTML = `
    <button id="leo-bubble" aria-label="Chat with Leo">
      <span id="leo-bubble-icon">🦁</span>
    </button>
    <div id="leo-drawer" role="dialog" aria-label="Leo Chat" hidden>
      <div id="leo-resize-handle"></div>
      <div id="leo-header">
        <span id="leo-header-title">🦁 Leo</span>
        <div id="leo-header-actions">
          <button id="leo-menu-btn" aria-label="More options">⋯</button>
          <button id="leo-close" aria-label="Close chat">✕</button>
        </div>
      </div>
      <div id="leo-menu" hidden>
        <button class="leo-menu-item" id="leo-menu-clear">🗑 Clear conversation</button>
        <button class="leo-menu-item" id="leo-menu-hotkey">⌨ Hotkeys: Send on press</button>
        <button class="leo-menu-item" id="leo-menu-powered">⚡ Powered by LeoAI</button>
      </div>
      <div id="leo-consent">
        <div id="leo-consent-body">
          <div id="leo-consent-title">Before we chat 👋</div>
          <p id="leo-consent-intro">Leo is an AI assistant. A few things you should know:</p>
          <ul id="leo-consent-points">
            <li>Leo is an AI, not a human — but he'll always be upfront about that.</li>
            <li>Your conversation is stored and may be reviewed by the business owner.</li>
            <li>A session token is saved in your browser so Leo can remember your conversation.</li>
            <li>No account or personal information is required to chat.</li>
          </ul>
          <button id="leo-consent-details-btn">See full privacy details ▾</button>
          <div id="leo-consent-details" hidden>
            <p>Leo is powered by LeoAI, built by Steadfast Code. Here's a fuller picture of how your data is handled:</p>
            <ul>
              <li><strong>What's stored:</strong> Your messages and Leo's replies are saved in a secure database, linked to an anonymous session token — not your name or identity.</li>
              <li><strong>Who can see it:</strong> The business owner whose site you're visiting can read conversation transcripts to improve their service and Leo's training.</li>
              <li><strong>Your session token:</strong> A small identifier is saved in your browser (localStorage) to keep your conversation continuous across visits. It's anonymous and never tied to personal data.</li>
              <li><strong>AI-generated responses:</strong> Leo's answers are generated by AI and may occasionally be inaccurate. Always verify important information directly with the business.</li>
              <li><strong>Data deletion:</strong> To request deletion of your conversation, contact the business directly.</li>
              <li><strong>No tracking:</strong> LeoAI does not use your data for advertising or sell it to third parties.</li>
            </ul>
          </div>
          <div id="leo-consent-actions">
            <button id="leo-consent-decline">No thanks</button>
            <button id="leo-consent-accept">Got it, let's chat</button>
          </div>
        </div>
      </div>
      <div id="leo-messages"></div>
      <div id="leo-input-row">
        <input id="leo-input" type="text" placeholder="Ask me anything..." autocomplete="off" />
        <button id="leo-send" aria-label="Send">Send</button>
      </div>
    </div>
  `;
  document.body.appendChild(container);

  // --- Element refs ---
  const bubble       = document.getElementById('leo-bubble');
  const drawer       = document.getElementById('leo-drawer');
  const closeBtn     = document.getElementById('leo-close');
  const resizeHandle = document.getElementById('leo-resize-handle');
  const menuBtn      = document.getElementById('leo-menu-btn');
  const menu         = document.getElementById('leo-menu');
  const consentEl    = document.getElementById('leo-consent');
  const messagesEl   = document.getElementById('leo-messages');
  const inputRow     = document.getElementById('leo-input-row');
  const input     = document.getElementById('leo-input');
  const sendBtn   = document.getElementById('leo-send');

  // --- Consent ---
  const CONSENT_KEY = `leo_consent_${domain}`;
  const hasConsented = () => localStorage.getItem(CONSENT_KEY) === 'true';

  function showConsent() {
    consentEl.style.display = 'flex';
    messagesEl.style.display = 'none';
    inputRow.style.display = 'none';
  }

  function showChat() {
    consentEl.style.display = 'none';
    messagesEl.style.display = '';
    inputRow.style.display = '';
  }

  function acceptConsent() {
    localStorage.setItem(CONSENT_KEY, 'true');
    showChat();
    input.focus();
    if (!historyLoaded) { historyLoaded = true; loadHistory(); initSocket(); }
  }

  // Initialize correct state on load
  if (!hasConsented()) {
    showConsent();
  } else {
    showChat();
  }

  document.getElementById('leo-consent-accept').addEventListener('click', acceptConsent);

  document.getElementById('leo-consent-decline').addEventListener('click', () => {
    drawer.hidden = true;
  });

  document.getElementById('leo-consent-details-btn').addEventListener('click', () => {
    const details = document.getElementById('leo-consent-details');
    const btn = document.getElementById('leo-consent-details-btn');
    details.hidden = !details.hidden;
    btn.textContent = details.hidden ? 'See full privacy details ▾' : 'Hide details ▴';
  });

  // --- Interactive options state ---
  let activeOptions = null; // { options, el, isYesNo, pendingValue }

  // --- History state ---
  let historyLoaded = false;
  let oldestTimestamp = null;
  let loadingHistory = false;
  let hasMoreHistory = false;

  async function loadHistory(before = null) {
    if (loadingHistory) return;
    loadingHistory = true;

    try {
      const params = new URLSearchParams({ domain, sessionToken });
      if (before) params.append('before', before);

      const res = await fetch(`${BACKEND_URL}/chat/history?${params}`);
      const data = await res.json();

      if (!data.messages?.length) return;

      hasMoreHistory = data.hasMore;

      // Preserve scroll position when prepending
      const prevHeight = messagesEl.scrollHeight;

      // Iterate in reverse so oldest ends up at the top after prepending
      for (let i = data.messages.length - 1; i >= 0; i--) {
        const msg = data.messages[i];
        const el = document.createElement('div');
        el.className = `leo-msg leo-msg--${msg.role}`;
        el.dataset.timestamp = msg.timestamp;
        if (msg.role === 'assistant') {
          el.appendChild(renderMarkdown(msg.content));
        } else {
          el.textContent = msg.content;
          if (msg.type === 'interactive') {
            const badge = document.createElement('span');
            badge.className = 'leo-interactive-badge';
            badge.textContent = '⚡';
            el.appendChild(badge);
          }
        }
        messagesEl.insertBefore(el, messagesEl.firstChild);
      }

      // Track oldest message for next page
      oldestTimestamp = data.messages[0].timestamp;

      // Restore scroll position so view doesn't jump
      if (before) {
        messagesEl.scrollTop = messagesEl.scrollHeight - prevHeight;
      } else {
        messagesEl.scrollTop = messagesEl.scrollHeight;
      }
      // Show greeting after initial history load
      if (!before) {
        const hasHistory = data.messages?.length > 0;
        const unseenReplies = data.unseenOwnerReplies || [];

        if (unseenReplies.length) {
          // Owner replied while visitor was away — lead with that
          const replyText = unseenReplies.length === 1
            ? `Welcome back! 👋 The ${data.entityName || 'team'} got back to you while you were away:\n\n"${unseenReplies[0]}"\n\nIs there anything else I can help with?`
            : `Welcome back! 👋 The team replied to your questions while you were away — scroll up to see their messages. Anything else I can help with?`;
          appendMessage('assistant', replyText);
        } else {
          const greeting = hasHistory && data.lastTopic
            ? `Welcome back! 👋 Last time we chatted about "${data.lastTopic}" — pick up where we left off or ask something new!`
            : hasHistory
            ? `Welcome back! 👋 Great to see you again. What can I help you with?`
            : `Hey there! 👋 I'm Leo, your AI assistant. What can I help you with today?`;
          appendMessage('assistant', greeting);
        }
      }
    } catch {
      // silently fail — history is nice to have, not critical
      if (!before) appendMessage('assistant', `Hey there! 👋 I'm Leo, your AI assistant. What can I help you with today?`);
    } finally {
      loadingHistory = false;
    }
  }

  // Load more history when user scrolls to the top
  messagesEl.addEventListener('scroll', () => {
    if (messagesEl.scrollTop === 0 && hasMoreHistory && !loadingHistory) {
      loadHistory(oldestTimestamp);
    }
  });

  // --- Toggle drawer ---
  bubble.addEventListener('click', () => {
    const isHidden = drawer.hidden;
    drawer.hidden = !isHidden;
    if (isHidden) {
      if (!hasConsented()) {
        showConsent();
      } else {
        messagesEl.hidden = false;
        inputRow.hidden = false;
        input.focus();
        if (!historyLoaded) { historyLoaded = true; loadHistory(); initSocket(); }
      }
    }
  });

  closeBtn.addEventListener('click', () => {
    drawer.hidden = true;
    menu.hidden = true;
  });

  // --- Resize handle ---
  const MIN_HEIGHT = 300;
  const MAX_HEIGHT = window.innerHeight - 120;

  resizeHandle.addEventListener('mousedown', (e) => {
    e.preventDefault();
    const startY = e.clientY;
    const startHeight = drawer.offsetHeight;

    function onMouseMove(e) {
      const delta = startY - e.clientY;
      const newHeight = Math.min(MAX_HEIGHT, Math.max(MIN_HEIGHT, startHeight + delta));
      drawer.style.height = newHeight + 'px';
    }

    function onMouseUp() {
      document.removeEventListener('mousemove', onMouseMove);
      document.removeEventListener('mouseup', onMouseUp);
    }

    document.addEventListener('mousemove', onMouseMove);
    document.addEventListener('mouseup', onMouseUp);
  });

  // --- Three-dot menu ---
  menuBtn.addEventListener('click', (e) => {
    e.stopPropagation();
    menu.hidden = !menu.hidden;
  });

  document.addEventListener('click', () => { menu.hidden = true; });
  menu.addEventListener('click', (e) => e.stopPropagation());

  document.getElementById('leo-menu-clear').addEventListener('click', () => {
    messagesEl.innerHTML = '';
    clearActiveOptions();
    localStorage.removeItem(SESSION_KEY);
    menu.hidden = true;
  });

  const hotkeyBtn = document.getElementById('leo-menu-hotkey');
  function updateHotkeyLabel() {
    const b = localStorage.getItem('leo_hotkey_behavior') || 'immediate';
    hotkeyBtn.textContent = b === 'immediate' ? '⌨ Hotkeys: Send on press' : '⌨ Hotkeys: Select then Enter';
  }
  updateHotkeyLabel();
  hotkeyBtn.addEventListener('click', () => {
    const cur = localStorage.getItem('leo_hotkey_behavior') || 'immediate';
    localStorage.setItem('leo_hotkey_behavior', cur === 'immediate' ? 'select' : 'immediate');
    updateHotkeyLabel();
    menu.hidden = true;
  });

  document.getElementById('leo-menu-powered').addEventListener('click', () => {
    window.open('https://steadfastcode.tech', '_blank');
    menu.hidden = true;
  });

  // --- Minimal markdown renderer ---
  function renderMarkdown(text) {
    const el = document.createElement('div');
    el.className = 'leo-markdown';

    // Escape HTML first
    let html = text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

    // Bold **text**
    html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    // Italic *text*
    html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
    // Inline code `code`
    html = html.replace(/`(.+?)`/g, '<code>$1</code>');

    // Convert lines to paragraphs / lists
    const lines = html.split('\n');
    const output = [];
    let inList = false;

    for (const line of lines) {
      const trimmed = line.trim();
      if (/^[-*•]\s+/.test(trimmed)) {
        if (!inList) { output.push('<ul>'); inList = true; }
        output.push(`<li>${trimmed.replace(/^[-*•]\s+/, '')}</li>`);
      } else {
        if (inList) { output.push('</ul>'); inList = false; }
        if (trimmed === '') {
          output.push('<br>');
        } else {
          output.push(`<p>${trimmed}</p>`);
        }
      }
    }
    if (inList) output.push('</ul>');

    el.innerHTML = output.join('');
    return el;
  }

  // --- Render a message bubble ---
  function appendMessage(role, text, interactivePayload = null) {
    const msg = document.createElement('div');
    msg.className = `leo-msg leo-msg--${role}`;
    if (role === 'assistant') {
      msg.appendChild(renderMarkdown(text));
    } else {
      msg.textContent = text;
      if (interactivePayload) {
        const badge = document.createElement('span');
        badge.className = 'leo-interactive-badge';
        badge.textContent = '⚡';
        msg.appendChild(badge);
      }
    }
    messagesEl.appendChild(msg);
    messagesEl.scrollTop = messagesEl.scrollHeight;
  }

  // --- Interactive option buttons ---
  function clearActiveOptions() {
    if (activeOptions?.el) activeOptions.el.remove();
    activeOptions = null;
  }

  function renderOptions(options) {
    clearActiveOptions();
    const isYesNo = options.length === 2 &&
      options[0].toLowerCase() === 'yes' && options[1].toLowerCase() === 'no';

    const wrap = document.createElement('div');
    wrap.className = 'leo-options';

    options.forEach((opt, i) => {
      const hotkey = isYesNo ? (i === 0 ? 'Y' : 'N') : String(i + 1);
      const btn = document.createElement('button');
      btn.className = 'leo-option-btn';
      btn.dataset.value = opt;
      btn.innerHTML = `<span class="leo-hotkey">${hotkey}</span>${opt}`;
      btn.addEventListener('click', () => selectOption(opt, options));
      wrap.appendChild(btn);
    });

    messagesEl.appendChild(wrap);
    messagesEl.scrollTop = messagesEl.scrollHeight;
    activeOptions = { options, el: wrap, isYesNo, pendingValue: null };
  }

  function selectOption(value, allOptions, fromKeyboard = false) {
    const behavior = localStorage.getItem('leo_hotkey_behavior') || 'immediate';
    if (!fromKeyboard || behavior === 'immediate') {
      clearActiveOptions();
      sendMessage(value, { options: allOptions, selected: value });
    } else {
      // Highlight selection, wait for Enter
      activeOptions.el.querySelectorAll('.leo-option-btn').forEach(b =>
        b.classList.toggle('leo-option-selected', b.dataset.value === value)
      );
      activeOptions.pendingValue = value;
    }
  }

  // Hotkey handler — active only when options are showing
  document.addEventListener('keydown', (e) => {
    if (!activeOptions || e.target === input) return;
    const { options, isYesNo, pendingValue } = activeOptions;
    const behavior = localStorage.getItem('leo_hotkey_behavior') || 'immediate';

    if (e.key === 'Enter' && behavior === 'select' && pendingValue) {
      e.preventDefault();
      const val = pendingValue;
      clearActiveOptions();
      sendMessage(val, { options, selected: val });
      return;
    }

    let matched = null;
    if (isYesNo) {
      if (e.key.toLowerCase() === 'y') matched = options[0];
      if (e.key.toLowerCase() === 'n') matched = options[1];
    } else {
      const num = parseInt(e.key);
      if (num >= 1 && num <= options.length) matched = options[num - 1];
    }
    if (matched) { e.preventDefault(); selectOption(matched, options, true); }
  });

  function setLoading(loading) {
    sendBtn.disabled = loading;
    input.disabled = loading;
    if (loading) {
      const dots = document.createElement('div');
      dots.className = 'leo-msg leo-msg--assistant leo-msg--typing';
      dots.id = 'leo-typing';
      dots.textContent = '…';
      messagesEl.appendChild(dots);
      messagesEl.scrollTop = messagesEl.scrollHeight;
    } else {
      document.getElementById('leo-typing')?.remove();
    }
  }

  // --- Send a message ---
  // text: optional pre-formed text (from option buttons); interactivePayload: metadata
  async function sendMessage(text, interactivePayload = null) {
    const message = text ?? input.value.trim();
    if (!message) return;

    clearActiveOptions();
    if (!text) input.value = '';
    appendMessage('user', message, interactivePayload);
    setLoading(true);

    try {
      const body = { domain, sessionToken, message };
      if (interactivePayload) {
        body.type = 'interactive';
        body.interactiveData = interactivePayload;
      }

      const res = await fetch(`${BACKEND_URL}/chat`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      });

      const data = await res.json();
      setLoading(false);

      if (data.reply) {
        appendMessage('assistant', data.reply);
        if (data.options?.length) renderOptions(data.options);
      } else {
        appendMessage('assistant', "Sorry, something went wrong. Please try again!");
      }
    } catch {
      setLoading(false);
      appendMessage('assistant', "I'm having trouble connecting right now. Please try again in a moment!");
    }
  }

  sendBtn.addEventListener('click', () => sendMessage());
  input.addEventListener('keydown', (e) => {
    if (e.key === 'Enter') sendMessage();
  });
})();
